ame: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
